language: cpp

env:

script:
- git log
- git branch -a
- git status
- git checkout develop
- pwd
- ls
- cd ..
- ls
- cd ..
- ls
- cd ..
- ls
- cd ..
- ls
- cd ..
- ls
- cd ..
- ls
- cd
- pwd
- ls
- echo $HOME
- which ctest
- which make
 
