git:
  depth: 1


language: cpp

notifications:
 email:
  on_success: never
  on_failure: never



env:

before_install:
- export DASHBOARD_ROOT=$(pwd)
- export SCRIPT_DIRECTORY=$DASHBOARD_ROOT/travis

# Uncomment the first time to build and install geant4 ; then it will be cached
#- travis_wait 45 /bin/bash $SCRIPT_DIRECTORY/geant4_build.sh 10.03.p03
- ls $HOME/geant4.10.03.p03/*
- source $HOME/geant4.10.03.p03/geant4.10.03.p03-install/bin/geant4.sh

# Uncomment the following lines the first time to build and install root ; then it will be cached
#- rm -rf $HOME/root
#- mkdir $HOME/root
#- cd $HOME/root
#- wget https://root.cern.ch/download/root_v6.10.06.Linux-ubuntu14-x86_64-gcc4.8.tar.gz 
#- tar -xvzf root_v6.10.06.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
#- mv root root_v6.10.06
- export ROOT_DIRECTORY=$HOME/root/root_v6.10.06
- source /home/travis/root/root_v6.10.06/bin/thisroot.sh

- find /usr/lib64 -name libsocket* -type f
- find / -name libsocket* -type f


# Uncomment these lines the first time to build and install ecat7 ; then it will be cached
- rm -rf $HOME/ecat7
- mkdir $HOME/ecat7
- cd $HOME/ecat7
- wget www.opengatecollaboration.org/sites/default/files/ecat.tar.gz
- tar -xvzf ecat.tar.gz
- export ECAT7_DIRECTORY=$HOME/ecat7
- cp Makefile.unix Makefile
- make
- cd utils
- cp Makefile.unix Makefile
- make
- cd ..
- mkdir include
- cp *.h include/
- mkdir lib
- cp libecat.a lib/



install:

cache:
- timeout: 2700
- directories:
  - $HOME/geant4.10.03.p03
  - $HOME/root
  - $HOME/ecat7

script:
- which git
- echo $DASHBOARD_ROOT
- echo $SCRIPT_DIRECTORY
- echo $ROOT_DIRECTORY
- echo $ECAT7_DIRECTORY
- echo $HOME

- ctest -S $SCRIPT_DIRECTORY/linux15_lin64/linux-gcc_4.8.3_ITKOFF-geant4_10.03.p03-opengate-public-develop.cmake -VV --output-on-failure
