git :
  depth : 1

language: cpp

env:

before_install:
- export cwd=$(pwd)
- export SCRIPTS=$cwd/travis

install :
#- $SCRIPTS/geant4_build.sh

script:
- echo $cwd
- echo $SCRIPTS
- git log
- pwd
- ls
- cd
- pwd
- ls
- echo $HOME
- which ctest
- which make

- echo $SCRIPTS
