git:
  depth: 1


language: cpp

compiler:
- gcc

notifications:
 email:
  on_success: never
  on_failure: never

env:

before_install:
- export DASHBOARD_ROOT=$(pwd)
- export SCRIPT_DIRECTORY=$DASHBOARD_ROOT/travis

# Uncomment this line the first time to build and install geant4 ; then it will be cached
#- travis_wait 45 /bin/bash $SCRIPT_DIRECTORY/geant4_build.sh 10.03.p03
- source $HOME/geant4.10.03.p03/geant4.10.03.p03-install/bin/geant4.sh

# Uncomment this line the first time to build and install root ; then it will be cached
#- /bin/bash $SCRIPT_DIRECTORY/root.sh
- export ROOT_DIRECTORY=$HOME/root/root_v6.10.06
- source /home/travis/root/root_v6.10.06/bin/thisroot.sh


# Uncomment this line the first time to build and install ecat7 ; then it will be cached
#- /bin/bash $SCRIPT_DIRECTORY/ecat7/ecat7.sh
- export ECAT7_DIRECTORY=$SCRIPT_DIRECTORY/ecat7

install:

cache:
- timeout: 2700
- directories:
  - $HOME/geant4.10.03.p03
  - $HOME/root
  - $HOME/ecat7

script:
- echo $DASHBOARD_ROOT
- echo $SCRIPT_DIRECTORY
- echo $ROOT_DIRECTORY
- echo $ECAT7_DIRECTORY
- echo $HOME

- ctest -S $SCRIPT_DIRECTORY/linux15_lin64/linux-gcc_4.8.3_ITKOFF-geant4_10.03.p03-opengate-public-develop.cmake -VV --output-on-failure
