git:
  depth: 1


language: cpp

notifications:
 email:
  on_success: never
  on_failure: never



env:

before_install:
- export DASHBOARD_ROOT=$(pwd)
- export SCRIPT_DIRECTORY=$DASHBOARD_ROOT/travis
- ls

#- travis_wait 45 /bin/bash $SCRIPT_DIRECTORY/geant4_build.sh 10.03.p03
# > $SCRIPT_DIRECTORY/geant4_install_log.txt 2>&1
- ls $HOME/geant4.10.03.p03/*
- less $SCRIPT_DIRECTORY/geant4_install_log.txt

- cd $HOME
- mkdir root
- cd root
- wget https://root.cern.ch/download/root_v6.10.06.Linux-ubuntu14-x86_64-gcc4.8.tar.gz 
- tar -xvzf root_v6.10.06.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
- mv root root_v6.10.06
- source /home/travis/root/root_v6.10.06/bin/thisroot.sh
- export ROOT_DIRECTORY=/home/travis/root/root_v6.10.06

install:

cache:
- timeout: 2700
- directories:
  - $HOME/geant4.10.03.p03
#  - $HOME/root

script:

#ctest -S $SCRIPT_DIRECTORY/linux15_lin64/linux-gcc_4.8.3_ITKOFF-geant4_10.03.p03-opengate-creatis-develop.cmake -VV --output-on-failure


- echo $DASHBOARD_ROOT
- echo $SCRIPT_DIRECTORY
- ls
- echo $HOME

