git:
  depth: 1

language: cpp

env:

before_install:
- export cwd=$(pwd)
- export SCRIPT_DIRECTORY=$cwd/travis

install :
#- $SCRIPT_DIRECTORY/geant4_build.sh

script:
- /bin/bash $SCRIPT_DIRECTORY/geant4_build.sh 10.03.p03
- cd $HOME
- cd geant4.10.03.p03
- tar -xvf geant4.10.03.p03.tar.gz
- ls

#/usr/bin/ctest -S $SCRIPT_DIRECTORY/linux15_lin64/linux-gcc_4.8.3_ITKOFF-geant4_10.03.p03-opengate-creatis-develop.cmake -VV --output-on-failure


- echo $cwd
- echo $SCRIPTS
- git log
- pwd
- ls
- cd
- pwd
- ls
- echo $HOME
- which ctest
- which make

- echo $SCRIPTS
- which bash
- ls /bin/bash

